### PR TITLE
Add/nvme support

### PR DESCRIPTION
**Pull request by langizoli**
Hello there,

I've added nvme support for the exporter.
It currently exports the following values: smart_status passed, critical_warning, available_spare, media_errors

I've also created a docker file which can be used to create a docker container from the exporter. I'm not a developer myself so if any corrections needed, happy to do it.

### CODE REVIEW

**Comment by r0arkin** [comment]
Hello! Can we get this PR in? This would be really useful to have!

**Comment by mr-yaky** [comment]
yes, will be really good to have it on upstream!

**Comment by mr-yaky** [comment]
@Sheridan Many thanks for the really nice exporter ! (Спасибо большое!)
I have used it with changes from this PR and it works nice. Also thank you @langizoli for the NVMe support!

I found only one strange behavior which I can't fix yet. When I have a server with both types of SSD drives, SATA + NVMe, then I always have a crashing of exporter:

```
# /opt/smartctl-exporter/smartctl_exporter -config=/etc/smartctl_exporter.yaml
[Warning] S.M.A.R.T. output reading error: exit status 1
[Warning] S.M.A.R.T. output reading error: exit status 1
panic: runtime error: index out of range [0] with length 0

goroutine 22 [running]:
main.(*SMARTctlInfo).mineVersion(0xc0000dceb8)
	/go/src/github.com/langizoli/smartctl_exporter/smartctlinfo.go:46 +0x942
main.(*SMARTctlInfo).Collect(...)
	/go/src/github.com/langizoli/smartctl_exporter/smartctlinfo.go:35
main.SMARTctlManagerCollector.Collect(0xc00022e060)
	/go/src/github.com/langizoli/smartctl_exporter/main.go:34 +0x1af
github.com/prometheus/client_golang/prometheus.DescribeByCollect.func1(0xa69ec0, 0xe0f3e0, 0xc00022e060)
	/go/src/github.com/prometheus/client_golang/prometheus/collector.go:90 +0x3b
created by github.com/prometheus/client_golang/prometheus.DescribeByCollect
	/go/src/github.com/prometheus/client_golang/prometheus/collector.go:89 +0x75
``` 
Config File:
```
smartctl_exporter:
  bind_to: "0.0.0.0:9633"
  url_path: "/metrics"
  fake_json: no
  smartctl_location: /usr/sbin/smartctl
  collect_not_more_than_period: "20s"
  devices:
  - /dev/sdb
  - /dev/sdc
```
And it doesn't matter if those existed NVMe drives enabled in config or not. It always gives me this error. 

all disks on server:
```bash
# lsblk -l|egrep -oe '(sd[a-z]|nvme[0-9])'|sed -e 's/^/  - \/dev\//'| uniq
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
  - /dev/nvme3
  - /dev/nvme4
``` 

I thought may be it can be related to this PR changes, so I compiled original version without NVMe supports. But unfortunately I have the same problem somehow:

```
# /opt/smartctl-exporter/smartctl_exporter -config=/etc/smartctl_exporter.yaml -debug
[Panic] Failed parse %!s(*string=0xc0001f21f0): %!s(<nil>)
[Debug] Parsed options: {{0.0.0.0:9633 /metrics %!s(bool=false) /usr/sbin/smartctl 20s 20s [/dev/sdb /dev/sdc]}}
[Debug] Collecting S.M.A.R.T. counters, device: /dev/sdb
[Warning] S.M.A.R.T. output reading error: exit status 1
[Debug] Collecting S.M.A.R.T. counters, device: /dev/sdc
[Warning] S.M.A.R.T. output reading error: exit status 1
panic: runtime error: index out of range [0] with length 0

goroutine 22 [running]:
main.(*SMARTctlInfo).mineVersion(0xc0000deeb8)
	/go/src/github.com/Sheridan/smartctl_exporter/smartctlinfo.go:46 +0x942
main.(*SMARTctlInfo).Collect(...)
	/go/src/github.com/Sheridan/smartctl_exporter/smartctlinfo.go:35
main.SMARTctlManagerCollector.Collect(0xc000232060)
	/go/src/github.com/Sheridan/smartctl_exporter/main.go:34 +0x1af
github.com/prometheus/client_golang/prometheus.DescribeByCollect.func1(0xa69ec0, 0xe0f3e0, 0xc000232060)
	/go/src/github.com/prometheus/client_golang/prometheus/collector.go:90 +0x3b
created by github.com/prometheus/client_golang/prometheus.DescribeByCollect
	/go/src/github.com/prometheus/client_golang/prometheus/collector.go:89 +0x75
```
It's really strange. BTW I have tested on 5 different servers and 3 of them have this mixed type of SSD drives and have this problem. But 2 other servers only with NMVe and work well:

```bash
# lsblk -l|egrep -oe '(sd[a-z]|nvme[0-9])'|sed -e 's/^/  - \/dev\//'| uniq
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
  - /dev/nvme3
  - /dev/nvme4

# cat /etc/smartctl_exporter.yaml 
# Ansible managed
smartctl_exporter:
  bind_to: "0.0.0.0:9633"
  url_path: "/metrics"
  fake_json: no
  smartctl_location: /usr/sbin/smartctl
  collect_not_more_than_period: "20s"
  devices:
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
  - /dev/nvme3
  - /dev/nvme4
``` 

```
# /opt/smartctl-exporter/smartctl_exporter -config=/etc/smartctl_exporter.yaml -debug
[Debug] Parsed options: {{0.0.0.0:9633 /metrics %!s(bool=false) /usr/sbin/smartctl 20s 20s [/dev/nvme0 /dev/nvme1 /dev/nvme2 /dev/nvme3 /dev/nvme4]}}
[Debug] Collecting S.M.A.R.T. counters, device: /dev/nvme0
[Debug] Collecting S.M.A.R.T. counters, device: /dev/nvme1
[Debug] Collecting S.M.A.R.T. counters, device: /dev/nvme2
[Debug] Collecting S.M.A.R.T. counters, device: /dev/nvme3
[Debug] Collecting S.M.A.R.T. counters, device: /dev/nvme4
[Info] Starting on 0.0.0.0:9633/metrics
^C
```

I have no idea why it happens with mixed type of SSD drives. I used the same ansible role which I developed for all 5 severs but the behavior is different. I mean the problem not in permissions or some Selinux staff.
Can you help me with this please ? I can provide some more info or will be able to do some other tests.
I already tested it on CentOS 7 with smartmontools-7.0-2.el7.x86_64.

**Comment by mr-yaky** [comment]
Well, finally I found the problem on my end. I had different versions. On some hosts smartctl was pre-installed and had 6.5 version.

smartctl 7.0 2018-12-30 r4883 
smartctl 6.5 2016-05-07 r4318
smartctl 6.5 2016-05-07 r4318
smartctl 7.0 2018-12-30 r4883 
smartctl 6.5 2016-05-07 r4318

**Comment by Sheridan** [comment]
I am ashamed. Sorry for the long reaction ...

**Pull request merged**
